version: "3.3"

services:

  traefik:
    image: "traefik:v2.4"
    container_name: "traefik"
    command:
      - "--log.level=INFO"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "8000:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - gateway

  ntcore:
    image: "ntcore/webserver:latest"
    container_name: "ntcore-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ntcore.rule=PathPrefix(`/`)"
      - "traefik.http.routers.ntcore.entrypoints=web"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - data:/usr/src/app/data
      - "./app-config/ntcore.yml:/usr/src/app/app-config/ntcore.yml"
    networks:
      - gateway

networks:
  gateway:
    driver: bridge

volumes:
  data: