---
kind: ConfigMap
apiVersion: v1
metadata:
  name: ntcore
data:
  ntcore.yml: |
    container:
      provider:
        type: kubernetes
        namespace: default
    database:
      provider: 
        type: postgres
        config: 
          host: localhost
          port: 5432
          user: postgres
          database: postgres
          password: ntcore
