modelServing:
  name: ${name}-core
  image: ${image}
  ports:
    - name: web
      containerPort: ${*targetPort}
  env:
  volumeMounts:
    - name: ${name}
      mountPath: /models
  readinessProbe:
    httpGet: 
      path: ${healthCheckPath}
      port: ${*targetPort}
    initialDelaySeconds: ${*initialDelaySeconds}
    periodSeconds: ${*periodSeconds}
  resources:
    requests:

bootstrap:
  name: ${name}-bootstrap
  image: ntcore/bootstrap
  args: 
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep infinity
  env:
    - name: DSP_API_ENDPOINT
      value: ntcore:8180
    - name: DSP_WORKSPACE_ID
      value: ${workspaceId}
  volumeMounts:
    - name: ${name}
      mountPath: /models
  readinessProbe:
    exec: 
      command: 
        - cat
        - /tmp/healthy
    initialDelaySeconds: ${*initialDelaySeconds}
    periodSeconds: ${*periodSeconds}

metricsProxy:
  name: ${name}-proxy
  image: ntcore/metrics-proxy
  ports:
    - name: web
      containerPort: ${*listenPort}
  args: 
    - mitmdump
    - -s
    - /usr/local/bin/metrics_collector.py
    - --listen-port
    - ${listenPort}
  env:
    - name: DSP_MONITORING_ENDPOINT
      value: ntcore-monitoring:8180
    - name: DSP_WORKSPACE_ID
      value: ${workspaceId}
    - name: DSP_BACKEND_PORT
      value: ${targetPort}
  readinessProbe:
    httpGet: 
      path: ${healthCheckPath}
      port: ${*listenPort}
    initialDelaySeconds: ${*initialDelaySeconds}
    periodSeconds: ${*periodSeconds}