---
kind: ConfigMap
apiVersion: v1
metadata:
  name: ntcore
data:
  ntcore.yml: |
    container:
      provider:
        type: kubernetes
        config:
          namespace: ntcore
      images:
        sklearn: ntcore/fast-sklearn
        tensorflow: tensorflow/serving
        pytorch: pytorch/torchserve
        bootstrap: ntcore/bootstrap
        metricsProxy: ntcore/metrics-proxy
    database:
      provider:
        type: dynamodb
        config:
          region: us-east-1
    storage:
      provider:
        type: s3
        config:
          bucket: ntcore-model-storage
          root: binary
          region: us-east-1
    account: 
      username: ntcore
  
  serving.yml: |
    tensorflow:
      targetPort: 8501
      sourcePath: /s/${workspaceId}/predict
      targetPath: /v1/models/${workspaceId}:predict
      healthCheckPath: /v1/models/${workspaceId}
      environment:
        - name:  MODEL_NAME
          value: ${workspace_id}
    pytorch:
      targetPort: 8501
      sourcePath: /s/${workspaceId}/predict
      targetPath: /v1/models/${workspaceId}:predict
      healthCheckPath: /v1/models/${workspaceId}
      environment:
        - name:  MODEL_NAME
          value: ${workspace_id}
    sklearn:
      targetPort: 8501
      sourcePath: /s/${workspaceId}/predict
      targetPath: /v1/models/${workspaceId}:predict
      healthCheckPath: /v1/models/${workspaceId}
      environment:
        - name:  MODEL_NAME
          value: ${workspace_id}
