---
kind: ConfigMap
apiVersion: v1
metadata:
  name: ntcore
data:
  ntcore.yml: |
    container:
      provider:
        type: kubernetes
        config:
          namespace: default
      images:
        sklearn: ntcore/fast-sklearn
        tensorflow: ntcore/tensorflow-serving
        pytorch: ntcore/fast-torch
    database:
      provider:
        type: dynamodb
        config:
          region: 'cn-northwest-1'
    storage:
      provider:
        type: volume
        config:
          root: data/binary
    account:
      username: ntcore
